### ISSUE TITLE
please tag release 0.07 in git

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-Log-Any-Adapter-Screen#1]
Hi,

Metacpan has a newer version than tagged here.  Please tag it here, to ease tracking and packaging (I am right now packaging initially for Debian).

Thanks for a nice piece of code :-)

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

I believe all tags have been pushed now (the latest is v0.13).

You're welcome, and thanks!
